### ISSUE TITLE
how to do this?

### ISSUE THREAD

**Issue by yagobski** [zinok/ZohoBooksApi#2]
How can i call this using your syntax???

Email an invoice
POST  /invoices/:invoice_id/email
Email an invoice to the customer. Input json string is not mandatory. If input json string is empty, mail will be send with default mail content.

Parameters

send_customer_statement boolean Send customer statement pdf a with email.
send_attachment boolean Send the invoice attachment a with the email.

**Comment by zinok** [comment]
For all non-common methods you can call it like:

```
$api = new ZohoBooksApi($authToken, $orgId);
$api->makeApiRequest('/invoices/:invoice_id:/email', 'POST', $parameters);
```

Where $parameters contains send_customer_statement and  send_attachment keys.

**Comment by yagobski** [comment]
Thanks
